site_name: GEMINI Documentation

theme: 
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
  font:
    text: Poppins
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/gemini_small_logo.png
  logo: assets/gemini_logo.png

plugins:
  - search
  - glightbox
  - mkdocs-pdf


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
